name: Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run_code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies 
        run: python -m pip install build pytest # `build` for building our package and `pytest` to run test suite; we might need to install other test packages such as pytest-cov if James uses any others
      - name: Build and install package in container # the package is not ready to test by defualt, we have to build it and then install it first
        run: (python -m build --wheel && python -m pip install dist/*) # I belive `python -m build` builds the package in dist/ which it creates
      - name: Run tests
        run: python -m pytest -cov # not totally sure about this because I don't know what the final test suite directory structure will look like -- we'll know once James pushes. I'm assuming we'll have a test/ directory with a collection of .py files


