name: Code Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run_code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies 
        run: python -m pip install build pytest expects
      - name: Build and install package in container
        run: (python -m build --wheel && python -m pip install dist/*)
      - name: Run Code Coverage
        run: python -m pytest --cov=autodiff_team29 tests/
      - name: Extract Line Converage Percent
        run:  COV_PCT=$(python -m pytest --cov=autodiff_team29/ tests/ | grep TOTAL | awk '{print$4}'| grep '[0-9]')
      - name: Determine Pass Fail
        run:  if [[ COV_PCT >=90 ]] ; then exit 0; else exit 1; fi


